#!/bin/bash

# Parameters:
# $1 project
# $2 ref
# $3 username
# $4 sha

# Verify that the push is for the current branch
branch=$(sed -ne "s,^ref: \(.*\)$,\1,p" .git/HEAD)
[ "${branch}" == "$2" ] || exit 0

# Do the update, capturing to the log as it goes.
cat << EOF >> update.log

$(date)
$@
EOF
git pull >> update.log 2>&1 || exit -1
bower install >> update.log 2>&1 || exit -2
npm install >> update.log 2>&1 || exit -3
polymer build index.html >> update.log 2>&1 || exit -4

# Fix-ups due to `polymer build` issues with <base href="/"> and shared-bundle.html
touch build/bundled/shared-bundle.html
sed -i -e "s,<script>'base href=\"/\"';</script>,<base href=\"/\">,g" build/bundled/index.html

echo "Success: $(date)" >> update.log
touch trigger-restart
